export type status = {
  active: string;
  servicing: string;
};

export type ItemType = {
  id: number;
  dueDate: string;
  loanFile: boolean;
  termSheet: boolean;
  draws: boolean;
  relatedTo: string;
  address: string;
  borrowerName: string;
  status: status;
  action: string;
};

export const TableData: ItemType[] = [
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maric Senter",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Maryland Winkle",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Krishna Barbe",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "9996 - Cox - 20 Upper",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Roselle Ehrman",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: false,
    draws: false,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Charolette Hanlin",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
  {
    id: 1235,
    dueDate: "12.01.2024",
    loanFile: true,
    termSheet: true,
    draws: true,
    relatedTo: "9996 - Cox - 20 Upper",
    address: "20 Upper Neck Street",
    borrowerName: "Kylee Danford",
    status: { active: "Active", servicing: "Servicing" },
    action: "Contact",
  },
];
